spring:
  profiles:
    active: dev

server:
  port: 8080

#mybatis:
#  mapper-locations: classpath:mappers/*.xml  #指定Mybatis的Mapper文件
#  type-aliases-package: com.jiayun.erp.wms.mybatis.entity #指定Mybatis的实体目录
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml  #指定Mybatis的Mapper文件
  type-aliases-package: com.jiayun.erp.wms.mybatis.entity #指定Mybatis的实体目录

#认证token有效期(token缓存有效期) 10 * 24 * 60 * 60 单位：S
auth-token-expiration: 864000
#缓存有效期 1 * 24 * 60 * 60
cache-expiration: 86400


