spring:
  profiles:
    active: dev

server:
  port: 8080


#mybatis:
#  mapper-locations: classpath:mappers/*.xml  #指定Mybatis的Mapper文件
#  type-aliases-package: com.jiayun.erp.wms.mybatis.entity #指定Mybatis的实体目录
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml  #指定Mybatis的Mapper文件
  type-aliases-package: com.jiayun.erp.wms.mybatis.entity #指定Mybatis的实体目录