spring:
  datasource:
    name: wms
    url: jdbc:mysql://localhost:3306/wms?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: false  #开发环境热部署
      additional-paths: src/main/java
      exclude: static/**
  mvc:
    #static-path-pattern: /** #指定前端访问后台静态资源的位置，默认为/**，需要前端增加路径时，如localhost/img/1.jpg，则配置为/img/**
  web:
    resources:
      #static-locations: classpath:/static/  #指定其他静态资源位置
  servlet:
    multipart:
      max-file-size: 10MB #请求中每个文件大小，注：一次请求可以有多个文件
      max-request-size: 11MB  #每个请求大小

upload-dir: /upload-file/

